### ISSUE TITLE
Scipy.random.permutation problem

### ISSUE THREAD

**Issue by beratyenilen** [dilinanp/chook#1]
I recently downloaded the package to test it out for my research and I noticed an error. 
In tile_planting.py, line 329 the code tries to use scipy.random.permutation function but this yields an error since the late versions of Scipy don't support this. I simply import numpy and used numpy.random.permutation instead, which I think fixed the problem. 
I experienced the same problem with K_LOCAL problem and I just changed the wishart_planting.py line 33 to np.random.choice.

**Comment by s-mandra** [comment]
Thanks! The problems has been fixed in #2.
